# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beam_rf_qt.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrBeam(object):
    def setupUi(self, FrBeam):
        FrBeam.setObjectName("FrBeam")
        FrBeam.resize(800, 550)
        FrBeam.setMinimumSize(QtCore.QSize(800, 550))
        FrBeam.setMaximumSize(QtCore.QSize(800, 550))
        font = QtGui.QFont()
        font.setPointSize(12)
        FrBeam.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon1/icons/steel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FrBeam.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(FrBeam)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 30, 251, 221))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.comboBox_bs = QtWidgets.QComboBox(self.tab)
        self.comboBox_bs.setGeometry(QtCore.QRect(10, 50, 91, 22))
        self.comboBox_bs.setObjectName("comboBox_bs")
        self.comboBox_cs = QtWidgets.QComboBox(self.tab)
        self.comboBox_cs.setGeometry(QtCore.QRect(140, 50, 91, 22))
        self.comboBox_cs.setStyleSheet("")
        self.comboBox_cs.setObjectName("comboBox_cs")
        self.label_bs = QtWidgets.QLabel(self.tab)
        self.label_bs.setGeometry(QtCore.QRect(10, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_bs.setFont(font)
        self.label_bs.setObjectName("label_bs")
        self.label_cs = QtWidgets.QLabel(self.tab)
        self.label_cs.setGeometry(QtCore.QRect(140, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_cs.setFont(font)
        self.label_cs.setObjectName("label_cs")
        self.tabWidget.addTab(self.tab, "")
        self.lineEdit_h = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_h.setGeometry(QtCore.QRect(300, 90, 113, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_h.setFont(font)
        self.lineEdit_h.setObjectName("lineEdit_h")
        self.label_h = QtWidgets.QLabel(self.centralwidget)
        self.label_h.setGeometry(QtCore.QRect(300, 60, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_h.setFont(font)
        self.label_h.setStyleSheet("")
        self.label_h.setObjectName("label_h")
        self.lineEdit_bw = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_bw.setGeometry(QtCore.QRect(450, 90, 113, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_bw.setFont(font)
        self.lineEdit_bw.setObjectName("lineEdit_bw")
        self.label_bw = QtWidgets.QLabel(self.centralwidget)
        self.label_bw.setGeometry(QtCore.QRect(460, 60, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_bw.setFont(font)
        self.label_bw.setObjectName("label_bw")
        self.lineEdit_d = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_d.setGeometry(QtCore.QRect(600, 90, 113, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_d.setFont(font)
        self.lineEdit_d.setObjectName("lineEdit_d")
        self.label_d = QtWidgets.QLabel(self.centralwidget)
        self.label_d.setGeometry(QtCore.QRect(600, 60, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_d.setFont(font)
        self.label_d.setObjectName("label_d")
        self.lineEdit_md = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_md.setGeometry(QtCore.QRect(300, 160, 113, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_md.setFont(font)
        self.lineEdit_md.setObjectName("lineEdit_md")
        self.label_md = QtWidgets.QLabel(self.centralwidget)
        self.label_md.setGeometry(QtCore.QRect(300, 130, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_md.setFont(font)
        self.label_md.setObjectName("label_md")
        self.pushButton_hesapla = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hesapla.setGeometry(QtCore.QRect(300, 210, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_hesapla.setFont(font)
        self.pushButton_hesapla.setObjectName("pushButton_hesapla")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 270, 701, 209))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 10, 10, 5)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_a = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_a.setFont(font)
        self.label_a.setObjectName("label_a")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_a)
        self.label_as = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_as.setFont(font)
        self.label_as.setObjectName("label_as")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_as)
        self.label_as_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_as_2.setFont(font)
        self.label_as_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_as_2.setText("")
        self.label_as_2.setObjectName("label_as_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_as_2)
        self.label_rf = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_rf.setFont(font)
        self.label_rf.setObjectName("label_rf")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_rf)
        self.label_rf_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_rf_2.setFont(font)
        self.label_rf_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_rf_2.setText("")
        self.label_rf_2.setObjectName("label_rf_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_rf_2)
        self.label_do = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_do.setFont(font)
        self.label_do.setObjectName("label_do")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_do)
        self.label_do_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_do_2.setFont(font)
        self.label_do_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_do_2.setText("")
        self.label_do_2.setObjectName("label_do_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_do_2)
        self.label_text = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_text.setFont(font)
        self.label_text.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_text.setText("")
        self.label_text.setObjectName("label_text")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_text)
        self.label_a_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_a_2.setFont(font)
        self.label_a_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_a_2.setText("")
        self.label_a_2.setObjectName("label_a_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_a_2)
        self.label_error = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_error.setFont(font)
        self.label_error.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_error)
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(430, 210, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 20, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        FrBeam.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrBeam)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FrBeam)

    def retranslateUi(self, FrBeam):
        _translate = QtCore.QCoreApplication.translate
        FrBeam.setWindowTitle(_translate("FrBeam", "Tek Donatılı Dikdörtgen Kiriş Donatı Hesabı"))
        self.label_bs.setText(_translate("FrBeam", "Beton Sınıfı"))
        self.label_cs.setText(_translate("FrBeam", "Çelik Sınıfı"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("FrBeam", "MALZEME"))
        self.lineEdit_h.setToolTip(_translate("FrBeam", "birim = mm"))
        self.label_h.setToolTip(_translate("FrBeam", "Birim = mm"))
        self.label_h.setText(_translate("FrBeam", "Kiriş Yüksekliği"))
        self.lineEdit_bw.setToolTip(_translate("FrBeam", "birim = mm"))
        self.label_bw.setToolTip(_translate("FrBeam", "Birim = mm"))
        self.label_bw.setText(_translate("FrBeam", "Kiriş Genişliği"))
        self.lineEdit_d.setToolTip(_translate("FrBeam", "birim = mm"))
        self.label_d.setToolTip(_translate("FrBeam", "birim = mm"))
        self.label_d.setText(_translate("FrBeam", "Pas Payı"))
        self.lineEdit_md.setToolTip(_translate("FrBeam", "birim = kN.m"))
        self.label_md.setToolTip(_translate("FrBeam", "birim = kN.m"))
        self.label_md.setText(_translate("FrBeam", "Tasarım Momenti"))
        self.pushButton_hesapla.setToolTip(_translate("FrBeam", "HESAPLA"))
        self.pushButton_hesapla.setText(_translate("FrBeam", "HESAPLA"))
        self.pushButton_hesapla.setShortcut(_translate("FrBeam", "Return"))
        self.label_a.setText(_translate("FrBeam", "Basınç Bloğu Derinliği(a):"))
        self.label_as.setText(_translate("FrBeam", "Gerekli Donatı Alanı(As):"))
        self.label_rf.setText(_translate("FrBeam", "Seçilen Donatı:"))
        self.label_do.setText(_translate("FrBeam", "Donatı Oranı:"))
        self.pushButton_clear.setToolTip(_translate("FrBeam", "YENİLE"))
        self.pushButton_clear.setText(_translate("FrBeam", "YENİLE"))
        self.pushButton_clear.setShortcut(_translate("FrBeam", "Return"))
        self.label.setText(_translate("FrBeam", "Kiriş boyutları mm, Tasarım momenti kN.m birimindedir.!!"))
import icon1_rc
